version: "3.8"
services:
  app:
    container_name: tubes-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URI=mysql+pymysql://dev:dev_password@tubes-db:3306/tubes_devsecop_app
      - SECRET_KEY=test_secret_key
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    container_name: tubes-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tubes_devsecop_app
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev_password
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

networks:
  app-network:
