version: '3.8'

services:
  app:
    container_name: tubes-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - API_KEY=${API_KEY}
      - DATABASE_URI=${DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db

  db:
    container_name: tubes-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tubes_devsecop_app
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev_password
