version: "3.8"
services:
  app:
    container_name: tubes-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URI=mysql+pymysql://dev:dev_password@tubes-db:3306/tubes_devsecop_app
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: tubes-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tubes_devsecop_app
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev_password
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
