name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/*
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker and Docker Compose
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Verify Docker Installation
        run: |
          docker --version
          docker-compose --version

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    name: Test Stage
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker and Docker Compose
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Verify Docker Installation
        run: |
          docker --version
          docker-compose --version

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Start Docker Compose
        run: docker-compose up -d db

      - name: Wait for MySQL to be Ready
        run: sleep 30

      - name: Run Tests
        env:
          DATABASE_URI: mysql+pymysql://root:root@localhost:3306/tubes_devsecop_app
          SECRET_KEY: test_secret_key
        run: pytest --cov=app tests/

      - name: Stop Docker Compose
        run: docker-compose down

  sast:
    name: Security Scanning Stage (SAST)
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Bandit
        run: pip install bandit

      - name: Run SAST with Bandit
        run: bandit -r app/

  dast:
    name: Testing DAST Stage
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker and Docker Compose
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start Docker Compose
        run: docker-compose up -d app db

      - name: Wait for Application to be Ready
        run: sleep 30

      - name: Install OWASP ZAP CLI
        run: |
          sudo apt-get update
          sudo apt-get install zaproxy -y
          pip install python-owasp-zap-v2.4

      - name: Run DAST Scan
        run: |
          zap-cli quick-scan --self-contained --start-options '-daemon -config api.disablekey=true' http://127.0.0.1:5000

      - name: Stop Docker Compose
        run: docker-compose down

  deploy:
    name: Deployment Stage
    runs-on: ubuntu-latest
    needs: dast
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker and Docker Compose
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Deploy to Staging
        run: |
          docker-compose -f docker-compose.yml up -d
