name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Stage
        run: echo "Build stage completed!"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Tests
        run: echo "Test stage completed!"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deployment Stage
        run: echo "Deployment completed!"
