name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-22.04  # Atau ganti ke ubuntu-24.04 untuk mencoba versi terbaru
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip install -r requirements.txt

      - name: Run Build
        run: echo "Build stage completed!"
